// <auto-generated />
namespace MyNote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BillingAddressAddedToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BillingAddressAddedToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202002220939350_BillingAddressAddedToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
